### ISSUE TITLE
Error: Failed to fetch/Error: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by jjoshrtca** [lukstei/reddit-hyped-stocks#2]
After downloading the repository here on github.com, installing Python 3 from the website (not the Microsoft app store) and Node.js, installing the backend dependencies, using git bash to run start.sh, installing the frontend dependencies, and running frontend dev server (after successfully loading the data from the Reddit API), I get the following error in Edge: "Error: Failed to fetch" after opening http://localhost:3000/. I even tried Firefox and still get a similar error: "Error: NetworkError when attempting to fetch resource."

**Comment by lukstei** [comment]
Seems like the backend is not running

**Comment by douginoz** [comment]
Same problem:
Ubuntu 20.04
praw 7.1.6 (tried 7.2.0 as well)
python3.8
npm 6.14.4

all requirements loaded.
First I grab fresh data (I have also tried using the data.db.example data but get the same result):
```
moa@tiko:/opt/reddit-hyped-stocks/backend$ python3 load_data.py 
Querying Reddit API:  70%|███████████████████████████████████████████████████████████████▌                           | 699/1000 [00:12<00:05, 54.91it/s]
Successfully loaded data
Cleaning up old data

```

Then I run start.sh from backend directory:
```
moa@tiko:/opt/reddit-hyped-stocks/backend$ ./start.sh 
 * Serving Flask app "server" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 897-584-248
```
Then in another session I start up the frontend:
```
moa@tiko:/opt/reddit-hyped-stocks/frontend$ npm run start
> frontend@0.1.0 start /opt/reddit-hyped-stocks/frontend
> react-scripts start
Compiled successfully!

You can now view frontend in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.1.35:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

```
I get the browser window pop up and the reading/scanning/loading graphic zips across the screen, followed by:
`Error: NetworkError when attempting to fetch resource.`

And in the backend console is this stack dump:

```
127.0.0.1 - - [17/Mar/2021 02:32:22] "GET /settings/tickerClassifications HTTP/1.1" 200 -
127.0.0.1 - - [17/Mar/2021 02:32:23] "GET /scores HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moa/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moa/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moa/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moa/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moa/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/reddit-hyped-stocks/backend/server.py", line 104, in calculate
    return calculate_cached()
  File "/opt/reddit-hyped-stocks/backend/server.py", line 63, in calculate_cached
    score.ticker_score_df_rel.loc[
  File "/home/moa/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/moa/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/moa/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
My praw.ini file contains:
```
[ClientSecrets]
client_id=abcdefghijklmn
client_secret=abcdefghijklmnabcdefghijklmnabcdefghijklmn
user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:36.0) Gecko/20100101 Firefox/36.0'

```
Part of my load_data.py shows:
```
from models import mapper_registry, Posts

subreddits_to_load = ["robinhoodpennystocks", "pennystocks"]
posts_to_load = 1000
```

**Comment by douginoz** [comment]
I should add that while writing all that, the load_data.py suddenly stopped working:
```
moa@tiko:/opt/reddit-hyped-stocks/backend$ python3 load_data.py 
Querying Reddit API:   0%|                                                                                                     | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://www.reddit.com/api/v1/access_token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/requestor.py", line 54, in request
    return self._http.request(*args, timeout=timeout, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 381, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://www.reddit.com/api/v1/access_token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "load_data.py", line 44, in <module>
    load_data("+".join(subreddits_to_load), count=posts_to_load)
  File "load_data.py", line 24, in load_data
    posts = [{
  File "load_data.py", line 24, in <listcomp>
    posts = [{
  File "/home/moa/.local/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/moa/.local/lib/python3.8/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/moa/.local/lib/python3.8/site-packages/praw/models/listing/generator.py", line 73, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/moa/.local/lib/python3.8/site-packages/praw/reddit.py", line 566, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/moa/.local/lib/python3.8/site-packages/praw/reddit.py", line 666, in _objectify_request
    self.request(
  File "/home/moa/.local/lib/python3.8/site-packages/praw/reddit.py", line 848, in request
    return self._core.request(
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 324, in request
    return self._request_with_retries(
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 222, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 179, in _make_request
    response = self._rate_limiter.call(
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 277, in _set_header_callback
    self._authorizer.refresh()
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/auth.py", line 346, in refresh
    self._request_token(grant_type="client_credentials")
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/auth.py", line 30, in _post
    response = self._requestor.request(
  File "/home/moa/.local/lib/python3.8/site-packages/prawcore/requestor.py", line 56, in request
    raise RequestException(exc, args, kwargs)
prawcore.exceptions.RequestException: error with request Failed to parse: https://www.reddit.com/api/v1/access_token
```
I don't know what changed.  I was a bit confused with the installation instructions regarding setting up the client_id and client_secret.  When I created the reddit "app", it expected a "redirect uri".  I don't know what that is or what to use so I just put in anything ("http://blueskyretreat.netgear.com/hyped", which doesn't exist).  I didn't know what the client_id was so I used the random string displayed at the top of the 'Development Applications' box in the https://www.reddit.com/prefs/apps that got created when I created the type 'script'.  And for 'user_agent', I just used what I found [here](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes#parse-useragent) and placed it in quotes in the praw.ini file.

**Comment by lukstei** [comment]
The problem seems to be that the example data is already a few days old, therefore we get index errors - either you collect your own data or use the provided one which can be downloaded at https://drive.google.com/file/d/12aAc35F5a0_doGE7Af8xsukRyNKPo1g0/view?usp=sharing (see updated Readme)

**Comment by jjoshrtca** [comment]
> Seems like the backend is not running

How?  I typed start.sh and hit enter before moving on to step four and even after it didn't work I double clicked the file and saw the git bash window open and close.  How do I get/force it to run if not that?  Or how do I check/confirm that it's running?  (or could my error be due to something else?)  Thanks.

edit: I should say I reran the backend dependencies install and all lines came up as already satisfied, so there's nothing missing there.

edit2: I should preface this by saying I only know DOS commands and *some* basic Linux commands, but decided to try and see what was going on by starting the backend in a git bash window and this is what I got:

```
f0xh0@LAPTOP-27BLE8MQ MINGW64 ~
$ cd Downloads/reddit-hyped-stocks/backend/

f0xh0@LAPTOP-27BLE8MQ MINGW64 ~/Downloads/reddit-hyped-stocks/backend (main)
$ bash start.sh
start.sh: line 1: venv/bin/python: No such file or directory

f0xh0@LAPTOP-27BLE8MQ MINGW64 ~/Downloads/reddit-hyped-stocks/backend (main)
$ sh start.sh
start.sh: line 1: venv/bin/python: No such file or directory

f0xh0@LAPTOP-27BLE8MQ MINGW64 ~/Downloads/reddit-hyped-stocks/backend (main)
$ 
```

should that directory in the start.sh file be pointing somewhere else on my Windows PC?

edit3: Also tried just running server.py and it ran... sort of:

```
f0xh0@LAPTOP-27BLE8MQ:~/reddit-hyped-stocks/backend$ python3 server.py
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

but, of course, it's running on an invalid address.

**Comment by lukstei** [comment]
Your edit3 looks fine - the backend is then definitely running then - `0.0.0.0:5000` is also fine
Is your `data.db` in place?

**Comment by jjoshrtca** [comment]
> Your edit3 looks fine - the backend is then definitely running then - `0.0.0.0:5000` is also fine
> Is your `data.db` in place?

You're right.  I must've been so tired last night that I only tried 0.0.0.0:5000 knowing it wouldn't work and not localhost:5000 *facepalm* Db is in place -- updated it last night. Looks really cool! Thanks :)

Just wondering, why the start.sh step and not just run server.py with `python server.py`? Shell script must've not run correctly due to Windows and the way it installed Python or just Windows itself.

**Comment by qiuxiaomu** [comment]
> The problem seems to be that the example data is already a few days old, therefore we get index errors - either you collect your own data or use the provided one which can be downloaded at https://drive.google.com/file/d/12aAc35F5a0_doGE7Af8xsukRyNKPo1g0/view?usp=sharing (see updated Readme)

It does scrape the data we set up in load_data.py doesn't it ? If this is true then we have loaded our own data before start the backend server; so how's that throwing an index error? this confuses me a lot. I am assuming load_data.py loads and translates updated data from Reddit.

And I have just tried with your Google sample data as well, a 383 MB database file. I got the same index error (using the non-docker approach).

Right, so I just tested your procedure using docker as well and I failed with the same index error (with your data from your google drive). Please let me know if I have missed any critical step along the way.

With `run-server-docker.sh` I think I don't need to do any configuration (apart from optionally downloading your google drive data); the container shall just perfectly create a working setup that you have tested beforehand. I am not sure which part has gone wrong. 

I am using MX Linux (take it as Debian 10); python 3.8 in virtualenv (I am not using `venv` and I had to manually change that).
